Added distcheck for files listed in POTFILES.in.

diff --git a/c-pluff/trunk/Makefile.am b/c-pluff/trunk/Makefile.am
--- a/c-pluff/trunk/Makefile.am
+++ b/c-pluff/trunk/Makefile.am
@@ -25,6 +25,17 @@ examples-install: install
 dist-hook:
 	rm -f '$(distdir)/ABOUT-NLS'
 
+distcheck-hook:
+	files="`cd '$(srcdir)' && find console libcpluff loader -type f -name '*.[ch]' -exec grep -q '_(' '{}' \; -print`"; \
+	rc=0; \
+	for f in $$files; do \
+		if ! grep -q "$$f" '$(srcdir)/po/POTFILES.in'; then \
+			echo "$$f missing from POTFILES.in"; \
+			rc=1; \
+		fi; \
+	done; \
+	exit $$rc
+
 clean-local:
 	test ! -f examples/Makefile || (cd examples && $(MAKE) $(AM_MAKEFLAGS) clean)
 
