Minor build system fixes.

diff --git a/c-pluff/trunk/Makefile.am b/c-pluff/trunk/Makefile.am
--- a/c-pluff/trunk/Makefile.am
+++ b/c-pluff/trunk/Makefile.am
@@ -6,7 +6,7 @@
 
 ACLOCAL_AMFLAGS = -I m4
 
-SUBDIRS = libcpluff loader console po test po doc
+SUBDIRS = libcpluff loader console po test doc
 DIST_SUBDIRS = $(SUBDIRS) examples
 
 EXTRA_DIST = COPYRIGHT.txt INSTALL.txt ChangeLog.txt Roadmap.txt autogen.sh doxygen.footer doxygen.css plugin.xsd
@@ -27,14 +27,14 @@ dist-hook:
 
 distcheck-hook:
 	files="`cd '$(srcdir)' && find console libcpluff loader -type f -name '*.[ch]' -exec grep -q '_(' '{}' \; -print`"; \
-	rc=0; \
-	for f in $$files; do \
-		if ! grep -q "$$f" '$(srcdir)/po/POTFILES.in'; then \
-			echo "$$f missing from POTFILES.in"; \
-			rc=1; \
-		fi; \
-	done; \
-	exit $$rc
+		rc=0; \
+		for f in $$files; do \
+			if ! grep -q "$$f" '$(srcdir)/po/POTFILES.in'; then \
+				echo "$$f missing from POTFILES.in"; \
+				rc=1; \
+			fi; \
+		done; \
+		exit $$rc
 
 clean-local:
 	test ! -f examples/Makefile || (cd examples && $(MAKE) $(AM_MAKEFLAGS) clean)
